# Generated by Django 5.2.1 on 2025-07-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Minimal (1)'), (2, 'Low (2)'), (3, 'Medium (3)'), (4, 'High (4)'), (5, 'Critical (5)')], default=3),
        ),
    ]
